steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: bash
    args: ['-c', 'rm -rf node_modules && npm install']

  # Simplified build step
  - name: 'node:20'
    entrypoint: bash
    args: ['-c', 'npx vite build']
    env:
      - 'NODE_ENV=production'

  # Create necessary directories
  - name: 'node:20'
    entrypoint: mkdir
    args: ['-p', 'cache/processed_images', 'cache/split_images']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy azuki-tcg-generator-test \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --timeout=300s \
          --command="node" \
          --args="server.js" \
          --set-env-vars="NODE_ENV=production,PORT=8080"